export enum Method {
    GET = 'get',
    POST = 'post',
    PUT = 'put',
    PATCH = 'patch',
    DELETE = 'delete',
    OPTIONS = 'options',
    HEAD = 'head',
}

export enum HeaderName {
    ACCEPT = 'accept',
    ACCEPT_CHARSET = 'accept-charset',
    ACCEPT_ENCODING = 'accept-encoding',
    ACCEPT_LANGUAGE = 'accept-language',
    ACCEPT_RANGES = 'accept-ranges',
    ALLOW = 'allow',
    CACHE_CONTROL = 'cache-control',
    CONTENT_DISPOSITION = 'content-disposition',
    CONTENT_ENCODING = 'content-encoding',
    CONTENT_LENGTH = 'content-length',
    CONTENT_RANGE = 'content-range',
    CONTENT_TYPE = 'content-type',
    COOKIE = 'cookie',
    ETag = 'etag',
    HOST = 'host',
    IF_MODIFIED_SINCE = 'if-modified-since',
    IF_NONE_MATCH = 'if-none-match',
    LAST_MODIFIED = 'last-modified',
    LOCATION = 'location',
    RANGE = 'range',
    RATE_LIMIT_LIMIT = 'ratelimit-limit',
    RATE_LIMIT_REMAINING = 'ratelimit-remaining',
    RATE_LIMIT_RESET = 'ratelimit-reset',
    RETRY_AFTER = 'retry-after',
    SET_COOKIE = 'set-cookie',
    TRANSFER_ENCODING = 'transfer-encoding',
    X_FORWARDED_HOST = 'x-forwarded-host',
    X_FORWARDED_FOR = 'x-forwarded-for',
    X_FORWARDED_PROTO = 'x-forwarded-proto',
}
