# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [master, next, beta, alpha]
    pull_request:
        types: [ opened, synchronize ]

permissions:
    packages: write
    contents: write
    issues: write
    pull-requests: write

env:
    PRIMARY_NODE_VERSION: 18

jobs:
    install:
        name: Checkout and Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}

    lint:
        name: lint Package
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: Lint
                run: |
                    npm run lint

    build:
        name: Build Package
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}
            - name: Build
              uses: ./.github/actions/build

    tests:
        name: Test Package
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: Run tests
                run: |
                    npm run test

    docs:
        name: Build & deploy docs
        needs: [lint, tests]
        runs-on: ubuntu-latest
        if: ${{ github.ref_name == 'master' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}

            - name: Build
              run: npm run build --workspace=packages/docs

            - name: CNAME
              run: |
                  cd ./packages/docs/src/.vitepress/dist/
                  touch CNAME
                  echo "routup.net" > CNAME

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./packages/docs/src/.vitepress/dist

    coverage:
        name: Coverage
        needs: [lint, tests]
        runs-on: ubuntu-latest
        if: ${{ github.ref_name == 'master' }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: Coverage
                run: |
                    npm run test:coverage --workspace=packages/routup

            -   name: Upload report
                uses: codecov/codecov-action@v3.1.2
                with:
                    token: ${{ secrets.codecov }}
                    directory: ./packages/routup/coverage/
